### ISSUE TITLE
Generate helper based on existing tailwind configuration

### ISSUE THREAD

**Issue by jgornick** [Seb-GRAF/tailwind-helper#1]
I'd like this provide this helper for my specific tailwind configuration. Is it possible to generate what classes/values are configured for tailwind? 

After a quick scan, it looks like tailwindClasses is the file that drives which classes/values to use.

Thanks!

**Comment by Seb-GRAF** [comment]
> I'd like this provide this helper for my specific tailwind configuration. Is it possible to generate what classes/values are configured for tailwind?
> 
> After a quick scan, it looks like tailwindClasses is the file that drives which classes/values to use.
> 
> Thanks!

I’m not sure I fully understand, you would like to provide your own custom tailwind values and have it reflect on the different helpers? 

If yes then exactly, tailwindClasses.ts is the one providing it. Should I close the issue?

**Comment by jgornick** [comment]
Sorry for not getting back sooner. But yes, I was looking to generate tailwindClasses.ts based on my custom tailwind.config.js. It's all good though! Thank you for getting back to me!
