### ISSUE TITLE
Violation of Tailwind CSS Brand Usage.

### ISSUE THREAD

**Issue by joshmanders** [Seb-GRAF/tailwind-helper#2]
Hello, Sebastien!

I'd first like to start off by saying great work on this project, I was introduced to it today and it is absolutely wonderful!

Unfortunately I learned about it because someone submitted <sup>[1]</sup> it to be included in Awesome Tailwind CSS <sup>[2]</sup> and we have a policy of making sure that anything submitted falls in line with the Tailwind CSS Brand Usage guidelines <sup>[3]</sup>. Tailwind Helper sadly does not, though I did reach out to Adam and he said it is fine because it is not being monetized, but did express that they would prefer not to be confusing.

That being said, we did approve and merge the PR so Tailwind Helper IS on Awesome Tailwind CSS! But I just wanted to follow up with you and point out the issue incase you were unaware of it.

If you decide to rebrand, please do follow up on Awesome Tailwind CSS with a PR updating the link, as I would love to keep it there.

[1]: https://github.com/aniftyco/awesome-tailwindcss/pull/464
[2]: https://github.com/aniftyco/awesome-tailwindcss
[3]: https://tailwindcss.com/brand#usage

**Comment by Seb-GRAF** [comment]
Hey Josh, sorry for the late reply.
Yeah for sure I can think of a rebrand to comply with Tailwind guidelines. I didn't even think of the potential issue when I named it. Do you think the logo would still be fine? I'll submit a PR when I get the time :)

**Comment by joshmanders** [comment]
Hi @Seb-GRAF 

No worries, I never expect a reply right away. Don't feel obligated to oblige to my beck and call!

The logo looks fine to me, I don't think that'd have any issues, so I think you should be good.
